# Generated by Django 3.2.5 on 2021-07-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('email', models.TextField()),
                ('nome', models.TextField()),
                ('telefone', models.TextField()),
                ('cpf', models.TextField()),
                ('data_nascimento', models.DateField()),
            ],
        ),
    ]
