# Generated by Django 3.2.5 on 2021-07-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_tipo_usuario',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
