# Generated by Django 3.2.5 on 2021-07-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_id_tipo_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_tipo_usuario',
            new_name='tipo_usuario',
        ),
    ]
