# Generated by Django 3.2.5 on 2021-07-15 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_rename_id_tipo_usuario_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
    ]
