# Generated by Django 3.2.5 on 2021-07-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_tipo_usuario',
            field=models.IntegerField(default=0, verbose_name='id-tipo-usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(verbose_name='data-nascimento'),
        ),
    ]
