# Generated by Django 3.2.5 on 2021-07-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20210724_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.TextField(default='user.2021'),
        ),
    ]
