# Generated by Django 3.2.5 on 2021-07-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20210726_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_tipo_usuario',
            field=models.IntegerField(blank=True, verbose_name='id-tipo-usuario'),
        ),
    ]
