# Generated by Django 3.2.5 on 2021-07-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_alter_usuario_id_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_tipo_usuario',
            field=models.IntegerField(blank=True, default=1, verbose_name='id-tipo-usuario'),
        ),
    ]
