# Generated by Django 3.2.5 on 2021-07-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.TextField(verbose_name='nome-produto')),
                ('preco_produto', models.FloatField(default=0.0, verbose_name='preco-produto')),
                ('promocao', models.BooleanField(blank=True, default=False)),
                ('desconto', models.IntegerField(blank=True, default=0)),
                ('caminho_imagem', models.TextField(blank=True, null=True, verbose_name='caminho-imagem')),
            ],
        ),
    ]
